import LeanForty.Problem000665

#print axioms LeanForty.prime_block_le_seventh
#print axioms Erdos808.blockPrime_le_seventh_eventually
#print axioms Erdos808.counterLabel_injective
#print axioms Erdos808.counterGraph_edge_threshold_eventually
#print axioms Erdos808.counterGraph_output_small_eventually
#print axioms Erdos808.erdos808_disproved
#print axioms LeanForty.Problem000665.strong_sum_product_false
#print axioms LeanForty.Problem000665.explicit_counterexamples
#print axioms LeanForty.Problem000665.positive_injective_labels
